version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: "npm i"
      - run:
          name: "Launch Lint"
          command: "npm run lint"
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - rin: "npm i"
      - run:
          name: "Launch Test"
          command: "npm run test"
  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: "npm i"
      - run:
          name: "Launch Audit"
          command: "npm audit"

workflows:
  launch-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
